Docs
sb-Milky-Way/Comment pull request #13
Opened 2017-04-11 17:31 UTC by plxel

Добавил небольшую инструкцию по процессу разработки
Редактируйте, добавляйте, чего не хватает
Делал на Windows, возможно, на UNIX*  что-то отличается

2017-04-11 17:51 UTC, mibu5 requested changes
Все отлично, пару коментов только, Если с чем-то не согласен будем обсуждать.

2017-04-11 17:51 UTC, mibu5 commented on DevelopmentProcess.md
> +6. Разрабатываем, коммитим, пушим. Не забываем регулярно забирать обновления из master
Думаю нужно добавить команду для пуша ветки в репозторий с привязкой. `git push -u branch-name`

2017-04-11 17:51 UTC, mibu5 commented on DevelopmentProcess.md
> +9. Если всё ок и конфликтов нет, будет написано Able to merge, если есть конфликты, забираем изменения из master, резолвим конфликты, повторяем процесс с п.8
тоже команду как забрать изменения из мастера, например если мерджим то `git pull origin master`

2017-04-11 17:51 UTC, mibu5 commented on DevelopmentProcess.md
> +10. Назначаем пару Reviwers (plxel можно всегда добавлять и ещё кого-либо из доступных людей), для code review и одобрения мержа
Думаю назначать ревьюиров не обязательно, а просто в наш канал Телеграмми запостить ссылку на Пул Реквест и попросить заревьюить. тогда каждый может взять и сделать ревью!

2017-04-11 18:41 UTC, plxel commented
@mibu5 я обновил док

2017-04-12 17:21 UTC, cuidadoso approved these changes
Approve

2017-04-12 17:28 UTC, cuidadoso approved these changes

2017-04-12 17:44 UTC, mibu5 reviewed
Looks good to me!

2017-04-12 17:44 UTC, mibu5 commented on DevelopmentProcess.md
> +8. Идем в репозиторий на github.com и там видим кнопку "Compare & pull request", нажимаем
или в закладку branches проекта, иногда `"Compare & pull request"` может не появиться

2017-04-12 17:44 UTC, mibu5 approved these changes

2017-04-12 18:01 UTC, merged