reply form base
sb-Milky-Way/Comment pull request #17
Opened 2017-04-18 19:25 UTC by plxel

resizable textarea, avatar, send button, and "add attachment icon"

2017-04-18 21:39 UTC, 2f1e1e approved these changes

2017-04-19 08:36 UTC, mibu5 requested changes
Изначально коментарии оставлял как опциональные. Думал заапрувить, но это ленивый вариант. Использование float уже на данном этапе потребовало костылей. как для textarea так и height в комментах. Нужно как-то это переделать, испозовать   clearfix. для текс ареи может box-sizing изменить если не помещаеться или еще что-то подумать или использовать flexbox как решение для всего.

2017-04-19 08:36 UTC, mibu5 commented on src/ReplyForm/ReplyForm.css
> +      width: calc(100% - 34px);
1) Выглядит как костыль. :)
2) И поддержка будет только для современных браузеров.  т.е. плюем на ИЕ9?

2017-04-19 08:36 UTC, mibu5 commented on src/ReplyForm/ReplyForm.css
> +    float: left;
Когда используем float то наверное нужен тоже clearfix.

2017-04-19 08:36 UTC, mibu5 commented on src/ReplyForm/ReplyForm.css
> +    height:30px;
Это тоже выглядит как костыль. clearfix или вообще раз уже calc, то я за флексбокс.

2017-04-19 08:36 UTC, mibu5 commented on src/ReplyForm/ReplyForm.jsx
> +    const avatar = customAvatar || <div styleName="reply-form__avatar">{author.split('').shift().toUpperCase()}</div>;
может дефолтный аватар вынести как отдельный компонент? он используесся и в коменте и здесь. Возожмно форма как отдльный компонент и не нужна. Размышления в слух. Можно обсудить.

2017-04-19 08:36 UTC, mibu5 commented on src/ReplyForm/ReplyForm.jsx
> +              <button styleName="reply-form__footer-send-btn" onClick={onSend}>{sendBtnText}</button>
я думаю тянуть footer в каждом названии не нужно, просто reply-form__send-btn.
также с другие классы немного тоже смущают названиями, reply-form__footer-send и reply-form__footer-actions. нажатие на кнопку ведь тоже action. и reply-form__footer-send очень общее, может reply-form__button-container, в голову ничего правда не приходит.

2017-04-19 08:36 UTC, mibu5 commented on src/ReplyForm/ReplyForm.jsx
> +          <Textarea rows={3} placeholder={placeholder}></Textarea>
не совсем понятно целесообразность использование отдельного компонента для Textarea, когда это просто текстареа.

2017-04-19 08:45 UTC, plxel commented on src/ReplyForm/ReplyForm.jsx
> +              <button styleName="reply-form__footer-send-btn" onClick={onSend}>{sendBtnText}</button>
ок, подумаю
actions имелось в виду именно всякие опциональные кнопочки

2017-04-19 08:45 UTC, plxel commented on src/ReplyForm/ReplyForm.jsx
> +          <Textarea rows={3} placeholder={placeholder}></Textarea>
не совсем просто, это autoresizable textarea

2017-04-19 08:47 UTC, plxel commented on src/ReplyForm/ReplyForm.jsx
> +    const avatar = customAvatar || <div styleName="reply-form__avatar">{author.split('').shift().toUpperCase()}</div>;
дефолтный аватар наверно имеет смысл вынести

>  Возожмно форма как отдльный компонент и не нужна. 
не совсем понял, ReplyForm не нужна?

2017-04-19 08:48 UTC, plxel commented on src/ReplyForm/ReplyForm.css
> +      width: calc(100% - 34px);
согласен, костыль

2017-04-19 09:14 UTC, mibu5 commented on src/ReplyForm/ReplyForm.jsx
> +    const avatar = customAvatar || <div styleName="reply-form__avatar">{author.split('').shift().toUpperCase()}</div>;
Форма нужна, может просто иметь обертку которая будет коментом, а форму уже внутри подставлять вместо коментария.

2017-04-19 09:15 UTC, mibu5 commented on src/ReplyForm/ReplyForm.jsx
> +          <Textarea rows={3} placeholder={placeholder}></Textarea>
понял

2017-04-21 15:49 UTC, mibu5 approved these changes
до 20 посмотреть внимательно не успе, потом отдельно гляну

2017-04-21 15:58 UTC, merged